### ISSUE TITLE
Estudar WebRTC

### ISSUE THREAD

**Issue by RenanLorijola** [Teethew/streamchat#1]
Estudar os padrões e ferramentas do WebRTC

**Comment by Teethew** [comment]
Signaling do lado do servidor: https://medium.com/javarevisited/webrtc-signaling-server-example-using-spring-boot-efd5f067900a

**Comment by Teethew** [comment]
Necessário pra parte de signaling mencionado nessa página do WebRTC
https://webrtc.org/getting-started/peer-connections

**Comment by Teethew** [comment]
https://blog.devgenius.io/webrtc-chat-application-772539ae97b7
